/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formulaire.article;

import comptamatiere.ARTICLE;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PRINCE
 */
public class CorrectionStock extends javax.swing.JDialog {

    /**
     * Creates new form CorrectionStock
     */
    public CorrectionStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.getContentPane().setBackground(Color.white);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablearticle = new javax.swing.JTable();
        Correctionlot = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Correctionstock = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablestock = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Correction Stock");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Tablearticle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tablearticle);

        Correctionlot.setText("Correction des Lots");
        Correctionlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrectionlotActionPerformed(evt);
            }
        });

        jLabel2.setText("Etape:1");

        jLabel3.setText("Etape:2");

        Correctionstock.setText("Correction des Stocks");
        Correctionstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrectionstockActionPerformed(evt);
            }
        });

        tablestock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablestock);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Cette fenetre permet de mettre à jour des stocks non justes. Pour le faire suivez les étapes en ordres");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Correctionlot, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Correctionstock, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correctionlot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(Correctionstock))))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-670)/2, (screenSize.height-495)/2, 670, 495);
    }// </editor-fold>//GEN-END:initComponents
ARTICLE art= new ARTICLE();
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
          
            String req="select libarticle as Article,QTE as Aquit, SUM(QTE_SORTIE) as QteSortie,(QTE-SUM(QTE_SORTIE)) as QteRelle,(QTESTOCK) as StocktTHEORIQUE,detailbon.iddetailbon as ligne,detailsortie.type "+
                       
 "from" +
 " article,detailbon,detailsortie,sortie where article.idarticle=detailbon.idarticle and detailbon.iddetailbon=detailsortie.iddetailbon and detailsortie.idsortie=sortie.idsortie" +
" and valide=1 and type='BC' group by detailsortie.iddetailbon,detailsortie.type" +
" UNION (select libarticle,STOCKINIT,SUM(QTE_SORTIE),(STOCKINIT-SUM(QTE_SORTIE)),Qte_Res_StockInit,article.idarticle,detailsortie.type "+
                        
" from article,detailsortie,sortie where article.idarticle=detailsortie.idarticle and detailsortie.idsortie=sortie.idsortie and sortie.valide=1 AND TYPE='INIT'group by detailsortie.iddetailbon,detailsortie.type )order by Article";

           Tablearticle.setModel(art.getDefaulTableModel(req));
                   } catch (SQLException ex) {
            Logger.getLogger(CorrectionStock.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void CorrectionlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrectionlotActionPerformed
        // TODO add your handling code here:
          int reponse= JOptionPane.showConfirmDialog(this,"voulez-vous Appliquez la Correction des lots?","confirmation",JOptionPane.YES_NO_OPTION);
        if(reponse==JOptionPane.YES_OPTION){
            try {
               
                String valeurDetail[]=new String[2];
                int nbrow=Tablearticle.getRowCount();
                int k=0;
                for( k=0;k<nbrow;k++){
                    if(Tablearticle.getValueAt(k,art.getColumnByName(Tablearticle, "type")).toString().equalsIgnoreCase("BC")){
                     art.insUpdateDel("update detailbon set QTESTOCK="+Tablearticle.getValueAt(k,art.getColumnByName(Tablearticle, "QteRelle")).toString() +" where iddetailbon="+Tablearticle.getValueAt(k,art.getColumnByName(Tablearticle, "ligne")).toString());//Tablearticle.getValueAt(k,art.getColumnByName(Tablearticle, "QteRelle")).toString()+"where iddetailbon="+Tablearticle.getValueAt(k,art.getColumnByName(Tablearticle, "iddetailbon")).toString());
                    }else{
                    art.insUpdateDel("update article set Qte_Res_StockInit="+Tablearticle.getValueAt(k,art.getColumnByName(Tablearticle, "QteRelle")).toString() +" where idarticle="+Tablearticle.getValueAt(k,art.getColumnByName(Tablearticle, "ligne")).toString());//Tablearticle.getValueAt(k,art.getColumnByName(Tablearticle, "QteRelle")).toString()+"where iddetailbon="+Tablearticle.getValueAt(k,art.getColumnByName(Tablearticle, "iddetailbon")).toString());
                 }
                }
                JOptionPane.showMessageDialog(this,k +" Article Corrigé avec succes");
                Correctionlot.setEnabled(false);
                Correctionstock.setEnabled(true);
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage());
            }
        }
    }//GEN-LAST:event_CorrectionlotActionPerformed

    private void CorrectionstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrectionstockActionPerformed
        try {
            // TODO add your handling code here:
            tablestock.setModel(art.getDefaulTableModel("select libarticle,SUM(QTESTOCK) As quantite,article.idarticle as idart from detailbon,article where article.idarticle=detailbon.idarticle group by detailbon.idarticle "));
             int nbrow=tablestock.getRowCount();
                int k=0;
                for( k=0;k<nbrow;k++){
                    art.insUpdateDel("update article set STOCKACTU=Qte_Res_StockInit + "+tablestock.getValueAt(k,art.getColumnByName(tablestock, "quantite")).toString() +" where idarticle="+tablestock.getValueAt(k,art.getColumnByName(tablestock, "idart")).toString());//Tablearticle.getValueAt(k,art.getColumnByName(Tablearticle, "QteRelle")).toString()+"where iddetailbon="+Tablearticle.getValueAt(k,art.getColumnByName(Tablearticle, "iddetailbon")).toString());
                 
                }
                JOptionPane.showMessageDialog(this,k +" Stock mise à jour  avec succes");
        } catch (SQLException ex) {
            Logger.getLogger(CorrectionStock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CorrectionstockActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        Correctionstock.setEnabled(false);
        jLabel1.setBackground(Color.white);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorrectionStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorrectionStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorrectionStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorrectionStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CorrectionStock dialog = new CorrectionStock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Correctionlot;
    private javax.swing.JButton Correctionstock;
    private javax.swing.JTable Tablearticle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablestock;
    // End of variables declaration//GEN-END:variables
}
