
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADEBO
 */
public class Pannel1 extends javax.swing.JPanel {
  ImageIcon imagen;
    /**
     * Creates new form Pannel
     */
    public Pannel1(String nombre) {
        initComponents();
        imagen = new ImageIcon(getClass().getResource(nombre));
        setSize(imagen.getIconWidth(),imagen.getIconHeight());
    }

    Pannel1() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    @Override
    protected void paintComponent(Graphics g) {
        Dimension d =getSize();
        g.drawImage(imagen.getImage(), 0, 0,d.width ,d.height , this);
        setOpaque(false);
        super.paintComponent(g);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(700, 405));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
